name: posyandu_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hexcolor: ^3.0.1
  intl: ^0.17.0
  flutter_native_timezone: ^2.0.0
  date_picker_timeline: ^1.2.3
  syncfusion_flutter_datepicker: ^21.1.39

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
